apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-html-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-html
  template:
    metadata:
      labels:
        app: devops-html
    spec:
      containers:
      - name: devops-html-container
        image: shivadocker2997/devops-html-app:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devops-html-service
spec:
  type: LoadBalancer
  selector:
    app: devops-html
  ports:
  - protocol: TCP
    port: 80        # Service port
    targetPort: 80  # Container port
